import {
  CirclePlus,
  LayoutDashboard,
  Truck,
  Package,
  ShoppingCart,
  History,
  Building2,
  User,
  CircleDot,
  Settings2,
  BarChart3,
  Settings,
  Plus,
  Search,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ArrowLeft,
  ArrowRight,
  MoreHorizontal,
  Pencil,
  Trash2,
  Eye,
  Filter,
  Check,
  AlertTriangle,
  Info,
  Loader2,
  Camera,
  FileText,
  Wrench,
  RefreshCw,
  MapPin,
  Phone,
  Mail,
  Calendar,
  Gauge,
  Circle,
  CheckCircle2,
  XCircle,
  Clock,
  TrendingUp,
  IndianRupee,
  Download,
  Printer,
  ArrowUpDown,
  Upload,
  PackageMinus,
  Wallet,
  Power,
  PowerOff,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  truck: Truck,
  package: Package,
  "shopping-cart": ShoppingCart,
  history: History,
  "building-2": Building2,
  user: User,
  "circle-dot": CircleDot,
  "settings-2": Settings2,
  "bar-chart-3": BarChart3,
  settings: Settings,
  plus: Plus,
  "plus-circle": CirclePlus,
  search: Search,
  x: X,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "more-horizontal": MoreHorizontal,
  pencil: Pencil,
  "trash-2": Trash2,
  eye: Eye,
  filter: Filter,
  check: Check,
  "alert-triangle": AlertTriangle,
  info: Info,
  "loader-2": Loader2,
  camera: Camera,
  "file-text": FileText,
  wrench: Wrench,
  "refresh-cw": RefreshCw,
  "map-pin": MapPin,
  phone: Phone,
  mail: Mail,
  calendar: Calendar,
  gauge: Gauge,
  circle: Circle,
  "check-circle-2": CheckCircle2,
  "x-circle": XCircle,
  clock: Clock,
  "trending-up": TrendingUp,
  "indian-rupee": IndianRupee,
  download: Download,
  printer: Printer,
  "arrow-up-down": ArrowUpDown,
  upload: Upload,
  "package-minus": PackageMinus,
  wallet: Wallet,
  power: Power,
  "power-off": PowerOff,
};

export function Icon({
  name,
  className,
  size = 20,
}: {
  name: string;
  className?: string;
  size?: number;
}) {
  const LucideIcon = iconMap[name] ?? Circle;
  return <LucideIcon className={className} size={size} aria-hidden="true" />;
}